version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./tasks.db:/app/tasks.db
      - ./huggingface:/root/.cache/huggingface
    restart: always

  frontend:
    build:
      context: ./task-manager-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
